# Generated by Django 5.2.8 on 2026-05-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('journey_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
            ],
        ),
    ]
